//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

import com.chatapp.client.ByteSeq;
import com.chatapp.client.StringSeq;

/** @hidden */
public class _ChatPrxI extends com.zeroc.Ice._ObjectPrxI implements ChatPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;

    @Override
    public void sendVoiceNote(String username, String voiceRecipient, ByteSeq voiceData) {
        

        throw new UnsupportedOperationException("Unimplemented method 'sendVoiceNote'");
    }

    @Override
    public void createGroup(String groupName, StringSeq members) {
        

        
        throw new UnsupportedOperationException("Unimplemented method 'createGroup'");
    }

    @Override
    public void sendVoiceCall(String username, String callee, ByteSeq callVoiceData) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'sendVoiceCall'");
    }

    public static long getSerialversionuid() {
        return serialVersionUID;
    }


}
