//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public interface _ChatOperationsNC
{
    void sendMessage(String sender, String recipient, String content);

    void makeCall(String caller, String callee);

    void createGroup(String groupName, String[] members);

    void sendVoiceNote(String sender, String recipient, byte[] voiceData);
}
