//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public interface _ChatOperations
{
    void sendMessage(String sender, String recipient, String content, Ice.Current current);

    void makeCall(String caller, String callee, Ice.Current current);

    void createGroup(String groupName, String[] members, Ice.Current current);

    void sendVoiceNote(String sender, String recipient, byte[] voiceData, Ice.Current current);
}
