//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public final class ByteSeqHolder extends Ice.Holder<byte[]>
{
    public
    ByteSeqHolder()
    {
    }

    public
    ByteSeqHolder(byte[] value)
    {
        super(value);
    }
}
