//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public final class ByteSeqHelper
{
    public static void
    write(Ice.OutputStream ostr, byte[] v)
    {
        ostr.writeByteSeq(v);
    }

    public static byte[]
    read(Ice.InputStream istr)
    {
        byte[] v;
        v = istr.readByteSeq();
        return v;
    }
}
