//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ChatApp;

public interface Chat extends _ChatOperations, _ChatOperationsNC,
                              Ice.Object
{
    public static final String ice_staticId = "::ChatApp::Chat";

    public static final long serialVersionUID = 3900603051540357692L;
}
